name: CI

on: [push, pull_request]

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'liberica'
    - name: Build
      run: xvfb-run -a ./gradlew --info test all

    - uses: actions/upload-artifact@v1
      with:
        name: All binaries
        path: build/libs

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: build/libs/*

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'liberica'
    - run: ./gradlew test mac --info
      env:
        APPLE_USER: ${{ secrets.APPLE_USER }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}

    - uses: actions/upload-artifact@v1
      with:
        name: macOS binary
        path: build/libs

  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'liberica'
        architecture: x64
    - run: ./gradlew test win-installer --info

    - uses: actions/upload-artifact@v1
      with:
        name: Windows binaries
        path: build/libs
